apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-staging'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portfolio.castle-yein.com
      secretName: portfolio-tls-secret
  rules:
    - host: portfolio.castle-yein.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  name: http
