apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: portfolio
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJkb2NrZXItcmVnaXN0cnkuY2FzdGxlLXllaW4uc2l0ZSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWTJGemRHeGxPbk41YVRjd056RTVOaUU9IgogICAgICAgICAgICAgICAgfQogICAgICAgfQp9
type: kubernetes.io/dockerconfigjson
