apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: portfolio
  annotations:
    avp.kubernetes.io/path: 'secret/data/docker'
data:
  .dockerconfigjson: <path:secret/data/docker#.dockerconfigjson>
type: kubernetes.io/dockerconfigjson
