apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: docker-registry.castle-yein.site/portfolio
  newName: :docker-registry.castle-yein.site/portfolio
  newTag: production-main-27fd2e9
